# -*- coding: utf-8 -*-
"""TareaSimulacion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p9afi46YWaJ2s_r_4PSpBXSsBC6FMNFV

1. Con los datos de FIFA, organizar a los jugadores de acuerdo al peso en las siguientes escalas y generar un cuadro tipo PIE

**LIBRERIAS A UTILIZAR**
"""

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

"""**LECTURA DE DATOS**"""

data= pd.read_csv('/content/fifa_datos.csv')

data.head()

Dict = {1: 0, 2: 0, 3: 0, 4: 0}
print(Dict.get(1))

for i in range(len(data)):
  weight=str(data['Weight'].values[i])
  value= weight.split('l',1)[0]
  value=float(value)
  if(value<125):
    Dict[1]=Dict.get(1)+1
  elif(value>=125 and value<150):
    Dict[2]=Dict.get(2)+1
  elif(value>=150 and value< 175):
    Dict[3]=Dict.get(3)+1
  elif(value>=175):
    Dict[4]=Dict.get(4)+1

Dict

x= Dict.keys()
y= Dict.values()
print(x)
print(y)

"""**Genereacion de grafico de pastel**"""

label=["Debajo 125 Lbs","125-150","150-175","175 o superior"]
fig= plt.figure(figsize=(10,7))
myExplode= [0.1,0.1,0.1,0.1]
colors=['maroon','blue','yellow','green']
plt.pie(y,labels=label, explode=myExplode,autopct='%1.1f%%')
plt.title(' FIFA Weight soccer players')
plt.legend()
plt.show()

"""2. Generar un grafico de barras (histograma) de acuerdo a su habilidad(Overall) en base a los siguientes segmentos contando el numero de jugadores"""

df_overall= pd.DataFrame(data.groupby(['Overall'])['Overall'].count())
df_overall.columns= ['Count']
df_overall.reset_index(inplace=True)
df_overall.head()

fig= plt.figure(figsize=(15,7))
sns.barplot(x='Overall',y='Count',data= df_overall)
sns.set_style('darkgrid')
plt.show()

"""3. Investigar alguna herramienta o software que permita generar reportes con PYTHON utilizando CodeLabs"""